#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use GAR\Logger\Log;
use GAR\Repository\DatabaseUploader;

$dotenv = Dotenv::createImmutable(__DIR__ . '/');

if (file_exists(__DIR__ . '/.env')) {
  $dotenv->load();
}

Log::write('hello world');

$time = microtime(true);
(new \GAR\Util\XMLReader\XMLReaderClient())->run();

function convert($size)
{
  $unit=array('b','kb','mb','gb','tb','pb');
  return @round($size/pow(1024,($i=floor(log($size,1024)))),2).' '.$unit[$i];
}

echo PHP_EOL . 'Time to execute: ' . microtime(true) - $time . PHP_EOL;
echo PHP_EOL . 'Peak memory usage: ' . convert(memory_get_peak_usage(true)) . PHP_EOL;
