#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Dotenv\Dotenv;
use GAR\Logger\Log;
use GAR\Repository\DatabaseUploader;

$dotenv = Dotenv::createImmutable(__DIR__ . '/');

if (file_exists(__DIR__ . '/.env')) {
  $dotenv->load();
}

$uplodaer = new DatabaseUploader(new \GAR\Entity\EntityFactory());

$time = microtime(true);
$uplodaer->upload(new \GAR\Util\XMLReader\XMLReaderFactory());
echo PHP_EOL . 'Execution time: ' . microtime(true) - $time . ' s.' . PHP_EOL;
